### ISSUE TITLE
CPU: Apple M1

### ISSUE THREAD

**Issue by BracketMaster** [inv2004/bench_nim_build#25]
```
CPU: Apple M1
Cores: 8
RAM: 3612688384
Disk: APPLE SSD AP0256Q
OS: Darwin (20.3.0)
66.326 seconds: ./build_all.sh
19.451 seconds: ./koch temp -d:release
```

**Comment by BracketMaster** [comment]
BTW, ``echo 'Freq:' $((`sysctl -n hw.cpufrequency` / 1000000))``
doesn't work on M1.

``-bash: / 1000000: syntax error: operand expected (error token is "/ 1000000")``

**Comment by BracketMaster** [comment]
Mainly cuz Apple doesn't allow frequency probing on their M1 processor.
I still don't know what it's frequency is... I've heard both 1.5GHz and 3+GHz...

**Comment by inv2004** [comment]
@BracketMaster 
Did you run bash ninbench.sh?

I suppose it could be the issue if you run via zsh

**Comment by BracketMaster** [comment]
Yes. I had to comment out the `sysctl -n hw.cpufrequency` line.
The issue is that Apple hides system frequencies.

**Comment by BracketMaster** [comment]
This is only for their new ARM machines. I don't know
why the lock that down.

**Comment by BracketMaster** [comment]
On M1, ``sysctl -n hw.cpufrequency`` just returns ``""`

**Comment by inv2004** [comment]
Thank you. Fixed the script.

M1 looks impressive
