### ISSUE TITLE
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

### ISSUE THREAD

**Issue by Ambrion** [inv2004/bench_nim_build#51]
```
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
Cores: 12
Freq: 2600.000 MHz
Ram: 31Gi
Disk: ATA ST1000LM035-1RK172
OS: Linux (5.15.15-76051515-generic)
111,986 seconds: ./build_all.sh
35,919 seconds: ./koch temp -d:release
```

**Comment by inv2004** [comment]
Thank you. Looks like it is time to add separate field for cc version

**Comment by Ambrion** [comment]
My laptop has two drives, but the SSD is not shown in the result.

**Comment by Ambrion** [comment]
> Thank you. Looks like it is time to add separate field for cc version

Yes, with clang the result is much better. (:
https://github.com/inv2004/bench_nim_build/issues/53

"А в попугаях-то, я намного длиннее!" (с) мультфильм
